foreground              #e2e2e9
background              #1e1f25
selection_foreground    #dbe2f9
selection_background    #3f4759

cursor                  #aec6ff
cursor_text_color       #122f60

url_color               #dfbbde

active_border_color     #aec6ff
inactive_border_color   #44474f
bell_border_color       #ffb4ab

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #d8e2ff
active_tab_background   #2c4678
inactive_tab_foreground #c5c6d0
inactive_tab_background #1e1f25
tab_bar_background      #111318

mark1_foreground #122f60
mark1_background #aec6ff
mark2_foreground #293041
mark2_background #bfc6dc
mark3_foreground #402843
mark3_background #dfbbde

color0 #44474f
color8 #8e9099

color1 #ffb4ab
color9 #93000a

color2  #aec6ff
color10 #d8e2ff

color3  #dfbbde
color11 #fcd7fb

color4  #bfc6dc
color12 #dbe2f9

color5  #2c4678
color13 #455e91

color6  #3f4759
color14 #583e5a

color7  #c5c6d0
color15 #e2e2e9
