general { 
    lock_cmd = hyprctl switchxkblayout all 0 && hyprlock
    before_sleep_cmd = loginctl lock-session 
} 

listener {
    timeout = 300
    on-timeout = ~/.config/bin/brightnessctl-all.sh -s set 10
    on-resume = ~/.config/bin/brightnessctl-all.sh -r
}

listener { 
    timeout = 600 
    on-timeout = loginctl lock-session 
}

listener {
    timeout = 660
    on-timeout = hyprctl dispatch 'hl.dsp.dpms()'
    on-resume = hyprctl dispatch 'hl.dsp.dpms()' && ~/.config/bin/brightnessctl-all.sh -r
}

# listener {
    # timeout = 1800
    # on-timeout = systemctl suspend
# }
