require('conf/programs')
require('conf/monitors')
require('conf/autostart')
require('conf/env')
require('conf/appearance')
require('conf/input')
require('conf/binds')
require('conf/rules')

local demoTimer = hl.timer(function()
    hl.notification.create({ text = 'Сделай перерыв, отойди от монитора', timeout = 5000 })
end, { timeout = 50 * 60 * 1000, type = 'repeat' })
-- end, { timeout = 6000, type = 'repeat' })
