source = ~/.config/hypr/colors.conf

# Основные настройки
general {
    # disable_loading_bar = true
    hide_cursor = true
    ignore_empty_input = true
}

# Фон экрана блокировки
background {
    # path = /path/to/your/wallpaper.png  # Укажите путь к вашему изображению
    path = screenshot
    # color = rgba(25, 20, 20, 1.0)       # Цвет фона (если изображение не используется)
    blur_passes = 3
    blur_size = 3
}

# Поле ввода пароля
input-field {
    size = 150, 40                      # Размер поля ввода
    font_family = JetBrainsMono                  # Шрифт
    # color = rgba(200, 200, 200, 1.0)    # Цвет текста
    placeholder_text = Password         # Текст-заполнитель
    placeholder_color = $placeholder  # Цвет текста-заполнителя
    outline_thickness = 0               # Толщина обводки
    outer_color = $border  # Цвет обводки
    fade_timeout = 1000
    placeholder_text = <i>Input Password...</i> # Text rendered in the input box when it's empty.
    rounding = 20 # -1 means complete rounding (circle/oval)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty
    # shadow_passes = 10
    # shadow_size = 20
    # shadow_color = rgb(0,0,0)
    # shadow_boost = 1.6
    inner_color = $input-bg
    font_color = $input-fg
    check_color = $check
    fail_color = $fail
    capslock_color = $capslock # Цвет рамки при включенном Caps Lock
}

label {
    monitor =
    #clock
    text = cmd[update:1000] echo "$TIME"
    color = $fg
    font_size = 60
    # font_family = Fira Semibold
    # font_family = SF Pro Rounded Bold
    font_family = Ndot77JPExtended
    # font_family = Noto Sans
    # font_family = MesloLGS NF
    # position = -100, 70
    # font_weight = 10000
    position = 0, 100
    halign = center
    valign = center
    # shadow_passes = 5
    # shadow_size = 10
}

label {
    monitor =
    #clock
    text = cmd[update:1000] echo "$(date +'%a %-d %B')"
    color = $fg
    font_size = 30
    font_family = Ndot77JPExtended
    # font_family = SF Pro Rounded Bold
    # font_family = Fira Semibold
    # font_family = Noto Sans
    # font_family = MesloLGS NF
    # position = -100, 70
    position = 0, 45
    halign = center
    valign = center
    # shadow_passes = 5
    # shadow_size = 10
}

# Отображение раскладки клавиатуры
label {
    monitor = DP-1
    text = $LAYOUT
    color = $fg
    font_size = 13
    # font_family = SF Pro Rounded Bold
    font_family = Ndot77JPExtended
    position = -10, 10
    halign = right
    valign = bottom
}

label {
    monitor = DP-2
    text = $LAYOUT
    color = $fg
    font_size = 13
    font_family = SF Pro Rounded Bold
    font_family = Ndot77JPExtended
    position = 10, 10
    halign = left
    valign = bottom
}
