# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = waybar
exec-once = hyprpaper
exec-once = mako
exec-once = ydotoold
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = hypridle  # Демон для автоматической блокировки при бездействии
exec-once = clipse -listen # run listener on startup
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = hyprsunset
exec-once = sleep 2 && AmneziaVPN
exec-once = udiskie -a -N
exec-once = easyeffects --service-mode -w
exec-once = /usr/lib/xdg-desktop-portal-hyprland
exec-once = sleep 2 && /usr/lib/xdg-desktop-portal
exec-once = kdeconnectd

