hl.on('hyprland.start', function()
    hl.exec_cmd('waybar')
    hl.exec_cmd('hyprpaper')
    hl.exec_cmd('mako')
    hl.exec_cmd('ydotoold')
    hl.exec_cmd('/usr/lib/hyprpolkitagent/hyprpolkitagent')
    hl.exec_cmd('hypridle')
    hl.exec_cmd('clipse -listen')
    hl.exec_cmd('gnome-keyring-daemon --start --components=secrets')
    hl.exec_cmd('hyprsunset')
    hl.exec_cmd('udiskie -a -N')
    hl.exec_cmd('easyeffects --service-mode -w')
    hl.exec_cmd('/usr/lib/xdg-desktop-portal-hyprland')
    hl.exec_cmd('kdeconnectd')
    hl.exec_cmd('sleep 2 && /usr/lib/xdg-desktop-portal')
    hl.exec_cmd('sleep 2 && AmneziaVPN')
end)
