# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$
# windowrule = float, ^(org.telegram.desktop)$
# windowrule = size 1000 600, ^(org.telegram.desktop)$
# windowrule = center, ^(org.telegram.desktop)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

windowrule = float on, match:title Картинка в картинке
windowrule = size 400 225, match:title Картинка в картинке
windowrule = move 1492 827, match:title Картинка в картинке

windowrule = pseudo on, match:class ^(org.telegram.desktop)$
windowrule = size 450 800, match:class ^(org.telegram.desktop)$

windowrule = float on, match:class ^(com.ayugram.desktop)$
windowrule = size 935 600, match:class ^(com.ayugram.desktop)$
windowrule = center on, match:class ^(com.ayugram.desktop)$

windowrule = float on, match:class (clipse)
windowrule = center on, match:class (clipse)
windowrule = size 622 470, match:class (clipse)
windowrule = stay_focused on, match:class (clipse)

windowrule = opacity 0.7 override,match:class ^(org.gnome.Nautilus)$
windowrule = opacity 0.7 override,match:class ^(Spotify)$
windowrule = opacity 0.7 override,match:class ^(yandex-music)$
windowrule = opacity 0.7 override,match:class ^(com.obsproject.Studio)$

windowrule = opacity 1.0 override,match:class ^(kitty)$
windowrule = opacity 1.0 override,match:class ^(zen)$
windowrule = opacity 1.0 override,match:class ^(dev.zed.Zed)$
windowrule = opacity 1.0 override,match:class ^(org.telegram.desktop)$

windowrule = float on, match:class ^(com.gabm.satty)$
windowrule = min_size 700 350, match:class ^(com.gabm.satty)$

windowrule = pseudo on, match:class ^(Waydroid)$
windowrule = workspace 1, match:class ^(Waydroid)$
windowrule = size 438 1022, match:class ^(Waydroid)$

# windowrule = workspace special:magic, match:class ^(wttr.in)$
windowrule = float on, match:class ^(wttr.in)$
windowrule = size 1284 950, match:class ^(wttr.in)$
windowrule = center on, match:class ^(wttr.in)$

windowrule = float on, match:class ^(wttr.in0)$
windowrule = size 310 170, match:class ^(wttr.in0)$

windowrule = float on, match:class ^(qalc)$
windowrule = size 600 230, match:class ^(qalc)$
#windowrule = center on, match:class ^(qalc)$

windowrule = workspace special:magic, match:class ^(Spotify)$

layerrule = blur on, match:namespace logout_dialog
layerrule = blur on, match:namespace wofi
layerrule = blur_popups on, match:namespace waybar
layerrule = blur on, match:namespace notifications

layerrule = ignore_alpha 0, match:namespace wofi
layerrule = ignore_alpha 0, match:namespace waybar
layerrule = ignore_alpha 0, match:namespace notifications

layerrule = above_lock 2, match:namespace logout_dialog
