$bg = {{colors.surface.default.rgba | set_alpha: 0.4}}
$fg = {{colors.on_surface.default.rgba | set_alpha: 0.7}}

$input-bg = {{colors.surface.default.rgba | set_alpha: 0.2}}
$input-fg = {{colors.on_surface.default.rgba | set_alpha: 0.7}}

$border = {{colors.primary.default.rgb}}
$placeholder = {{colors.on_surface_variant.default.rgba | set_alpha: 0.5}}

$check = {{colors.primary.default.rgba | set_alpha: 0.2}}
$fail = {{colors.error.default.rgba | set_alpha: 0.2}}
$capslock = {{colors.tertiary.default.rgba | set_alpha: 0.2}}
